# Generated by Django 2.1.5 on 2019-02-01 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookings',
            options={'ordering': ('day_book',)},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('order_time',)},
        ),
    ]
