# Generated by Django 2.1.5 on 2019-02-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0003_auto_20190205_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_bev',
            field=models.CharField(choices=[('M', 'morning'), ('E', 'evening'), ('N', 'none')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='beverages',
            name='evening_bev',
            field=models.CharField(choices=[('3', '3'), ('4', '4'), ('7', '7'), ('8', '8'), ('Null', 'Null')], default='4', max_length=2),
        ),
        migrations.AlterField(
            model_name='beverages',
            name='morning_bev',
            field=models.CharField(choices=[('3', '3'), ('4', '4'), ('7', '7'), ('8', '8'), ('Null', 'Null')], default='3', max_length=2),
        ),
    ]
