# Generated by Django 2.1.5 on 2019-02-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0004_auto_20190212_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='beverages',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
