# Generated by Django 2.1.5 on 2019-02-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0005_beverages_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beverages',
            name='evening_bev',
            field=models.CharField(choices=[('C', 'Coffee'), ('T', 'Tea'), ('L', 'Lemonade'), ('G', 'GreenTea'), ('Null', 'Null')], default='T', max_length=2),
        ),
        migrations.AlterField(
            model_name='beverages',
            name='morning_bev',
            field=models.CharField(choices=[('C', 'Coffee'), ('T', 'Tea'), ('L', 'Lemonade'), ('G', 'GreenTea'), ('Null', 'Null')], default='C', max_length=2),
        ),
    ]
